name: Feature Request ✨
description: Suggest a new feature or improvement for HungryBox.
title: "[💎 FEATURE]: "
labels: enhancement, needs triage
assignees: ''

body:
  - type: markdown
    attributes:
      value: |
        **Thank you for suggesting a feature! Your ideas help make HungryBox even better.**

  - type: input
    id: feature-title
    attributes:
      label: 💡 Feature Title
      description: Give your feature a short and clear title.
      placeholder: "E.g., Add dark mode support"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 📝 Description
      description: Describe the feature or improvement you’re suggesting.
      placeholder: "What problem does this feature solve? How would it improve HungryBox?"
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: 🔍 Use Case
      description: Explain how this feature would be used or why it is valuable.
      placeholder: "E.g., This feature would allow users to..."
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 📂 Additional Context or Screenshots
      description: Add any other details or screenshots to help us understand your suggestion.
